# Generated by Django 4.2 on 2023-05-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='images/')),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
