# Generated by Django 4.2 on 2023-06-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pepsi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='vlog',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
